chore: release v0.1.0
supabase-community/storage-dart pull request #31
Opened 2022-04-20 07:35 UTC by dshukertjr

2022-07-16 20:58 UTC, Vinzent03 commented
May you add the changes of #29 to the new version and release it ?

2022-07-16 20:59 UTC, Vinzent03 commented
@dshukertjr  May you add the changes of #29 to the new version and release it ?

2022-07-18 01:35 UTC, dshukertjr commented
@Vinzent03 
Sounds good!

2022-07-18 10:22 UTC, bdlukaa requested changes

2022-07-18 12:42 UTC, dshukertjr commented on CHANGELOG.md
> +- BREAKING: error is now thrown instead of returned within the responses.
@bdlukaa Amazing idea! Adding it now!

2022-07-18 16:48 UTC, bdlukaa approved these changes

2022-07-30 00:50 UTC, bdlukaa approved these changes

2022-07-30 01:05 UTC, merged